import { describe, expect, it } from 'vitest';
import { buildAnalysisReport } from '../src/report/template.js';
import { runFullAnalysis } from '../src/market/index.js';
import { EMAIL_HTML_LIMIT } from '../src/report/html-kit.js';

const optsDrive = { productName: 'Victor Consultant', surface: 'drive' as const };
const optsEmail = { productName: 'Victor Consultant', surface: 'email' as const };

function sampleResult() {
  return runFullAnalysis(
    { AAPL: { avg_price: 100, units: 10 } },
    { AAPL: 150 },
    {
      AAPL: {
        ticker: 'AAPL',
        targetLowPrice: 140,
        targetMedianPrice: 160,
        targetMeanPrice: 160,
        targetHighPrice: 180,
      },
    },
  );
}

describe('buildAnalysisReport', () => {
  it('drive HTML is paper-light and names the product', () => {
    const html = buildAnalysisReport(sampleResult(), 'Jude', optsDrive);
    expect(html).toContain('Jude');
    expect(html).toContain('Victor Consultant');
    expect(html).toContain('#f7fafe');
    expect(html).toContain('FROZEN_DRIVE_OVERRIDE');
    expect(html).not.toContain('#0d1117');
    expect(html).not.toContain('WalletStreet');
    expect(html).not.toContain('Generated by Wallet Street');
  });

  it('email HTML stays under 80KB and keeps hex after stripping style', () => {
    const html = buildAnalysisReport(sampleResult(), 'Jude', optsEmail);
    expect(html.length).toBeLessThanOrEqual(EMAIL_HTML_LIMIT);
    expect(html).not.toContain('oklch(');
    const stripped = html.replace(/<style>[\s\S]*?<\/style>/g, '');
    expect(stripped).toMatch(/<td[^>]*style="/);
    expect(stripped).toContain('#171f30');
  });
});
