import {
  EMAIL_HTML_LIMIT,
  EMAIL_HTML_WARN,
  HEX_TOKENS,
  REPORT_CSS,
  REPORT_CSS_EMAIL,
  frozenDriveOverride,
} from './visual-css.js';

export type ReportSurface = 'drive' | 'email';

export interface ReportOpts {
  productName: string;
  surface: ReportSurface;
}

export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function formatPct(value: number): string {
  return (value >= 0 ? '+' : '') + value.toFixed(1) + '%';
}

export function formatUsd(value: number): string {
  return (
    '$' +
    value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
  );
}

export function signedColor(value: number): string {
  if (value > 0) return HEX_TOKENS.success;
  if (value < 0) return HEX_TOKENS.danger;
  return HEX_TOKENS.foreground;
}

const EMAIL_TD = `padding:6px 10px;border-bottom:1px solid ${HEX_TOKENS.border};color:${HEX_TOKENS.foreground}`;
const EMAIL_TH = `padding:6px 10px;border-bottom:1px solid ${HEX_TOKENS.border};color:${HEX_TOKENS.mutedForeground};font-size:11px;text-align:left`;

export function tdStyle(extra = ''): string {
  return extra ? `${EMAIL_TD};${extra}` : EMAIL_TD;
}

export function thStyle(): string {
  return EMAIL_TH;
}

export function wrapReportHtml(args: {
  title: string;
  surface: ReportSurface;
  maxWidthPx: 800 | 900 | 640 | 720;
  body: string;
}): string {
  const { title, surface, maxWidthPx, body } = args;
  if (surface === 'email') {
    const t = HEX_TOKENS;
    return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(title)}</title>
<style>${REPORT_CSS_EMAIL}</style>
</head>
<body>
<table role="presentation" width="${maxWidthPx}" cellpadding="0" cellspacing="0" style="margin:0 auto;width:${maxWidthPx}px;max-width:100%;background:${t.background};font-family:Georgia,system-ui,sans-serif;color:${t.foreground}">
<tr><td style="padding:20px">${body}</td></tr>
</table>
</body>
</html>`;
  }
  const override = frozenDriveOverride(maxWidthPx === 900 ? 900 : 800);
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width">
<title>${escapeHtml(title)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Inter:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
<style>${REPORT_CSS}\n${override}</style>
</head>
<body>
<div class="page">${body}</div>
</body>
</html>`;
}

export function driveMetric(label: string, value: string, sub?: string, tone?: 'up' | 'down'): string {
  const t = tone === 'up' ? ' up' : tone === 'down' ? ' down' : '';
  return `<div class="metric-card">
  <div class="label-eyebrow">${escapeHtml(label)}</div>
  <div class="metric-value${t}">${escapeHtml(value)}</div>
  ${sub ? `<div class="metric-sub">${sub}</div>` : ''}
</div>`;
}

export function emailMetric(label: string, value: string, sub?: string, color?: string): string {
  const t = HEX_TOKENS;
  const c = color ?? t.ink;
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid ${t.border};background:${t.card};margin:0 0 8px">
<tr><td style="padding:12px 14px">
<div style="font-size:11px;letter-spacing:0.12em;text-transform:uppercase;color:${t.mutedForeground}">${escapeHtml(label)}</div>
<div style="font-size:22px;color:${c};margin-top:6px">${escapeHtml(value)}</div>
${sub ? `<div style="font-size:12px;color:${t.mutedForeground};margin-top:4px">${sub}</div>` : ''}
</td></tr></table>`;
}

export function driveSection(index: string, title: string, inner: string, desc?: string): string {
  return `<div class="section-gap">
  <div class="label-eyebrow" style="color:var(--brand)">${escapeHtml(index)}</div>
  <h2><span class="bar" aria-hidden="true"></span>${escapeHtml(title)}</h2>
  ${desc ? `<p>${desc}</p>` : ''}
</div>
${inner}`;
}

export function emailSection(title: string, inner: string): string {
  const t = HEX_TOKENS;
  return `<div style="margin:18px 0 8px;font-size:18px;color:${t.ink}">${escapeHtml(title)}</div>${inner}`;
}

export function footerLine(productName: string): string {
  return `Generated by ${productName} · Equities: Yahoo Finance · Options: stored marks · Not financial advice`;
}

export function dropCaption(shown: number, total: number): string {
  return `Showing ${shown} of ${total} by value`;
}

export function enforceEmailSize(html: string, reduce: () => string): string {
  if (html.length <= EMAIL_HTML_LIMIT) {
    if (html.length >= EMAIL_HTML_WARN) {
      console.warn(`send_report HTML is ${html.length} bytes (warn at ${EMAIL_HTML_WARN}).`);
    }
    return html;
  }
  const reduced = reduce();
  if (reduced.length > EMAIL_HTML_LIMIT) {
    throw new Error(
      `Email HTML is ${reduced.length} bytes after drop order (limit ${EMAIL_HTML_LIMIT}).`,
    );
  }
  if (reduced.length >= EMAIL_HTML_WARN) {
    console.warn(`send_report HTML is ${reduced.length} bytes after drop (warn at ${EMAIL_HTML_WARN}).`);
  }
  return reduced;
}

export { EMAIL_HTML_LIMIT, HEX_TOKENS };
